#!/usr/bin/env python3
"""
Test audio generated by Android app
Place the WAV file from your app in this directory and run:
    python test_android_audio.py your_file.wav
"""

import sys
import subprocess
import os

if len(sys.argv) < 2:
    print("Usage: python test_android_audio.py <wav_file>")
    print("\nThis will test the audio with:")
    print("  1. Our proven decoder (parse_full_packet.py)")
    print("  2. Dire Wolf (atest.exe)")
    sys.exit(1)

wav_file = sys.argv[1]

if not os.path.exists(wav_file):
    print(f"Error: File not found: {wav_file}")
    sys.exit(1)

print("=" * 70)
print(f"Testing: {wav_file}")
print("=" * 70)

# Test 1: Our decoder
print("\n[Test 1] Our proven decoder:")
print("-" * 70)
result = subprocess.run(['python', 'parse_full_packet.py', wav_file])

# Test 2: Dire Wolf
print("\n[Test 2] Dire Wolf:")
print("-" * 70)
direwolf_path = r"C:\Users\Joshua\Downloads\direwolf-1.8.1-a231971_x86_64\direwolf-1.8.1-a231971_x86_64"
atest = os.path.join(direwolf_path, 'atest.exe')

if os.path.exists(atest):
    result = subprocess.run([atest, '-B', '1200', wav_file])
else:
    print(f"Dire Wolf not found at: {atest}")

print("\n" + "=" * 70)
print("Testing complete!")
print("=" * 70)
